"""Initial migration

Revision ID: 6bb5b5461254
Revises: 
Create Date: 2025-07-29 12:03:01.734242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bb5b5461254'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spectra',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('osc_ref', sa.String(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('x', sa.JSON(), nullable=False),
    sa.Column('y', sa.JSON(), nullable=False),
    sa.Column('redshift', sa.Float(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spectra_id'), 'spectra', ['id'], unique=False)
    op.create_index(op.f('ix_spectra_osc_ref'), 'spectra', ['osc_ref'], unique=False)
    op.create_table('user_models',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('model_path', sa.String(), nullable=False),
    sa.Column('class_mapping_path', sa.String(), nullable=False),
    sa.Column('input_shape_path', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_models_id'), 'user_models', ['id'], unique=False)
    op.create_index(op.f('ix_user_models_name'), 'user_models', ['name'], unique=False)
    op.create_index(op.f('ix_user_models_owner'), 'user_models', ['owner'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_models_owner'), table_name='user_models')
    op.drop_index(op.f('ix_user_models_name'), table_name='user_models')
    op.drop_index(op.f('ix_user_models_id'), table_name='user_models')
    op.drop_table('user_models')
    op.drop_index(op.f('ix_spectra_osc_ref'), table_name='spectra')
    op.drop_index(op.f('ix_spectra_id'), table_name='spectra')
    op.drop_table('spectra')
    # ### end Alembic commands ###
